block-beta
    columns 7
    Query space:2 Adapter space:2 Graph
    Query-- "input" -->Adapter
    Adapter-- "output" -->Graph

    classDef block height:48px,padding:8px;
    classDef hidden visibility:none;
    class Adapter block
    class Query hidden
    class Graph hidden
