block-beta
    columns 7
    Any space:2 Reader space:2 Graph
    Any-- "input" -->Reader
    Reader-- "output" -->Graph

    classDef block height:48px,padding:8px;
    classDef hidden visibility:none;
    class Reader block
    class Any hidden
    class Graph hidden
