block-beta
    columns 7
    URI space:2 Resolver space:2 URL
    URI-- "input" -->Resolver
    Resolver-- "output" -->URL

    classDef block height:48px,padding:8px;
    classDef hidden visibility:none;
    class Resolver block
    class URI hidden
    class URL hidden
