---
title: Data flow for runners
---
block-beta
  classDef block height:48px,padding:8px;

  columns 5
  space:2 Options space:2
  space:5
  Input space Program space Output
  space:5
  space:2 State space:2

  Options --> Program
  Input-- "input" -->Program
  Program-- "output" -->Output
  State --> Program

  Options[/"Options"\]
  Program["Runner"]
  Input[/"Code"/]
  Output[/"Result"/]
  State[("Environment")]
