---
title: Data flow for writers
---
block-beta
  classDef block height:48px,padding:8px;

  columns 5
  space:2 Options space:2
  space:5
  Input space Program space Output

  Options --> Program
  Input-- "input" -->Program
  Program-- "output" -->Output

  Options[/"Options"\]
  Program["Writer"]
  Input[/"Graph"/]
  Output[/"Any"/]
